### ISSUE TITLE
conda-forge feedstock?

### ISSUE THREAD

**Issue by untzag** [dib-lab/osf-cli#111]
I love your project! :heart_eyes: Seriously, it's exactly what I was dreaming of.

It would help my workflow if there was a conda-forge feedstock. I would be happy to be a feedstock maintainer if desired. Really it just boils down to making a new PR for each version bump.

**Comment by betatim** [comment]
That would be great!  I don't know very much about writing conda-forge recipes so if you'd like to take care of that, that would be great 👍

**Comment by untzag** [comment]
https://github.com/conda-forge/staged-recipes/pull/4003

**Comment by untzag** [comment]
the feedstock is live 🎉 

those using conda can install directly using `conda install -c conda-forge osfclient`

@betatim please let me know if you or others would like to be added as feedstock maintainers. this will give you write access to the [feedstock repository](https://github.comis /conda-forge/osfclient-feedstock) so that you can change the recipe as needed. if not I will continue to watch your updates and update the recipe in turn.

thanks again for making this fantastic tool---I'm really looking forward to using it
the projects I have been sharing via OSF are composed of rather complex file / folder structures, so it's a real boon to sync the entire structure quickly from the command line 

feel free to close

**Comment by betatim** [comment]
😍 Super! Thanks a lot for making this happen. I'm fine not being a owner for the feedstock repository. IMHO it is better to have someone who has the time/resources and knowledge to do something about things when they break then deadweight like me :)

let us know how using osfclient goes. I am sure there are still lots of ugly bits that need work
