### ISSUE TITLE
OSF webinar and user stories

### ISSUE THREAD

**Issue by betatim** [dib-lab/osf-cli#116]
A request for help :)

If you use osfclient for your research could you share some screenshots or anecdotes or the like about that? Some stories about what you use it for that work well and things that don't work well would be cool. 

This is for a short talk during a OSF webinar advertising `osfclient` to new users.

In general the plan for my talk is to:

* introduce `osfclient` motivated by "want to put large files into and out of OSF without having to click". <insert more stories/anecdotes>
* do a walk through of the CLI showing off some functionality
  - create a new project (web)
  - connect a empty github repo (web)
  - clone the project to laptop (osfclient)
  - upload a file to osfstorage (osfclient)
  - clone the project from a different computer (osfclient) (faked by going to a different directory)
  - add a file to the GitHub repo via GitHub (web)
  - fetch that file via osfclient to my laptop
* show that you could also use osfclient to build your own stuff (osfclient the library)
* point people to this repo as a way to contribute/learn more

**Comment by ctb** [comment]
when is this webinar?

On Fri, Oct 06, 2017 at 12:13:35AM -0700, Tim Head wrote:
> A request for help :)
> 
> If you use osfclient for your research could you share some screenshots or anecdotes or the like about that? Some stories about what you use it for that work well and things that don't work well would be cool. 
> 
> This is for a short talk during a OSF webinar advertising `osfclient` to new users.
> 
> In general the plan for my talk is to:
> 
> * introduce `osfclient` motivated by "want to put large files into and out of OSF without having to click". <insert more stories/anecdotes>
> * do a walk through of the CLI showing off some functionality
>   - create a new project (web)
>   - connect a empty github repo (web)
>   - clone the project to laptop (osfclient)
>   - upload a file to osfstorage (osfclient)
>   - clone the project from a different computer (osfclient) (faked by going to a different directory)
>   - add a file to the GitHub repo via GitHub (web)
>   - fetch that file via osfclient to my laptop
> * show that you could also use osfclient to build your own stuff (osfclient the library)
> * point people to this repo as a way to contribute/learn more
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/osf-cli/issues/116
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by betatim** [comment]
Next Tuesday

**Comment by untzag** [comment]
> "want to put large files into and out of OSF without having to click"

personally I'm most excited about cloning many files and complex folder structures

like OSF, but the web interface is shockingly poor if you need to upload hundreds of files in a complex folder structure ([for example](https://osf.io/ej2xe/))

making it easy to move from private git repos (where we write our papers) to osf storage is going to help us comply with our open source goals

**Comment by betatim** [comment]
Material from the webinar has been posted here: https://osf.io/tx8p9/
