### ISSUE TITLE
Upload a whole (tree of) folders

### ISSUE THREAD

**Issue by betatim** [dib-lab/osf-cli#18]
`osf upload` only works with single files.

Add support to allow the user to upload a folder and its contents or even a whole tree of folders.

**Comment by benlindsay** [comment]
This feature in my mind would add a huge amount of usability to this cli. My personal use case for this is that I have lots of small files in multilevel subdirectories in a project and I'd want to upload them all at the same time. I am very excited for this feature to be implemented.
