### ISSUE TITLE
Some basic next steps

### ISSUE THREAD

**Issue by ctb** [dib-lab/osf-cli#2]
- [x] Make username/password configurable
- [x] fix osfstorage/subdirectory problem
- [x] put under test, + travis

More broadly:
- [x] figure out auth/credentials grabbing, maybe w/dot-file

**Comment by betatim** [comment]
What do you mean with "osfstorage/subdirecotry problem"? One thing I can think of is that currently it will create empty directories for storages that are enabled but don't contain anything (aka there will always be a `osfstorage/` subdir).
