### ISSUE TITLE
`osf init` to help creating config files

### ISSUE THREAD

**Issue by betatim** [dib-lab/osf-cli#43]
Add a `osf init` command that asks the user some questions and creates a `.osfcli.config` in the current directory.

This should make it easier for users to setup things when they are new.

**Comment by gedankenstuecke** [comment]
What things should be in the `.osfcli.config` at the end of the day? Just the two files listed in the `README.md`?

**Comment by betatim** [comment]
Yes, so far this is the only things that are supported. Maybe in the future we add more but right now just these two things.

Maybe as a "stretch goal" we could investigate creating a project on osf.io for the user if they don't have one as part of init? Not looked into the API for that.

**Comment by gedankenstuecke** [comment]
Ok, have never done any so fancy Python stuff, but depending on how much openSNP stuff there's pressing tonight/tomorrow I'll have a look into it!

**Comment by betatim** [comment]
Can start small with using `input()` to read user's inputs and writing them to a file. Then tackle the API thing in a second PR.

**Comment by gedankenstuecke** [comment]
Closed by #58.
