### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by betatim** [dib-lab/osf-cli#44]
This project doesn't have a logo yet! No code writing required to contribute to this issue.

Collect ideas and examples here.

Maybe something that connects visually with https://osf.io/ so people realise that this is a tool for using with osf.io

The global sprint bright green and blue is pretty cool...maybe a bit hard on the eyes for the long term. Ideas welcome.

**Comment by gedankenstuecke** [comment]
Idea: Maybe give a brief description on what the *osf-cli* is supposed to achieve, so people who want to design a logo have some idea in which direction to design? 🙂

**Comment by betatim** [comment]
Good point, in general for the README as well.

**Comment by chanaysavoyen** [comment]
![osf-cli-logo-sketchs](https://cloud.githubusercontent.com/assets/29117801/26681732/6a67d266-46de-11e7-9b9f-c24798f0093b.png)

**Comment by gedankenstuecke** [comment]
These are really cool. I like the middle-row and lower row ones especially. Maybe one could add a white `$_` or similar on those screens somewhere to the left to highlight the command-line interface idea even more? 😄

**Comment by betatim** [comment]
Woah!

I like the bottom right best. I think.

**Comment by betatim** [comment]
Maybe swap the little arrows for the `$_` idea from @gedankenstuecke on the bottom left?

**Comment by chanaysavoyen** [comment]
I argree to forget the first row and the bottom left. I will put a $_ on the screen and try add some of the bright green on it.

**Comment by betatim** [comment]
Ah, I was thinking keep the bottom left example, remove the small white arrows and then put the `$_` on the dark background instead.

Looking forward to your next iteration.

**Comment by chanaysavoyen** [comment]
The bottom left (from the first exemple) with the symbol looks too much as a price sticker. May be this sketch still remind me it, but it looks fresh and happy with the green color added (especially the second row who looks like a japanese emoji).

![osf-cli-logo-sketchs-v2](https://cloud.githubusercontent.com/assets/29117801/26685949/cda17460-46eb-11e7-864b-04bb2091f9d2.png)

**Comment by betatim** [comment]
The one with `>_` are kinda neat. How do you think things will go if we make them smaller?

I also like the top left.

**Comment by gedankenstuecke** [comment]
:+1: to the top left!

**Comment by La0** [comment]
:+1: on top left.

**Comment by chanaysavoyen** [comment]
So the top left it is? What filetype? svg, png? If png what size are needed?

**Comment by betatim** [comment]
SVG so we can make other sizes later?

PNG size, something that would work in the readme?

**Comment by betatim** [comment]
We can also post it here https://github.com/mozilla/global-sprint/issues/123 so we can be on pulse :)

**Comment by nkmeyers** [comment]
@chanaysavoyen  et al, I like the ones with >_   too 

 but was consensus topleft? 

the ones with  >_ somehow also recall for me with their "domed heads" and descending proboscis the "chad" doodle or the [kilroy was here](https://en.wikipedia.org/wiki/Kilroy_was_here) doodle ? 

Thanks! these are all great.

**Comment by chanaysavoyen** [comment]
I put a white border on the logo but it's can easely be removed if its not usefull.
[osf-cli-logo-v1-svg](https://chanaysavoyen.com/Mozilla/OSF-CLI/LOGO-v1/osf-cli-logo-v1.svg)
[osf-cli-logo-v1-png](https://chanaysavoyen.com/Mozilla/OSF-CLI/LOGO-v1/osf-cli-logo-v1.png)
![osf-cli-logo-v1](https://cloud.githubusercontent.com/assets/29117801/26713193/93186fda-476b-11e7-836a-e196401852a8.png)

**Comment by gedankenstuecke** [comment]
That's beautiful! 👍  💖  🍰

**Comment by betatim** [comment]
Nice!

nitpick: the white arrows now cut out a small part from the two blue blobs on the side and they got thicker too? I preferred the previous one.

**Comment by chanaysavoyen** [comment]
Files have been updated:
[osf-cli-logo-v1-svg](https://chanaysavoyen.com/Mozilla/OSF-CLI/LOGO-v1/osf-cli-logo-v1.svg)
[osf-cli-logo-v1-png](https://chanaysavoyen.com/Mozilla/OSF-CLI/LOGO-v1/osf-cli-logo-v1.png)
![osf-cli-logo-v1](https://cloud.githubusercontent.com/assets/29117801/26716881/882d67dc-477b-11e7-95b5-702d95956d79.png)

**Comment by betatim** [comment]
Do you want to make a PR to add it to the repo or should I take care of that?

**Comment by chanaysavoyen** [comment]
I did a the PR #59 is it fine?

**Comment by betatim** [comment]
Fixed in #59
