### ISSUE TITLE
Tests still fail locally

### ISSUE THREAD

**Issue by gedankenstuecke** [dib-lab/osf-cli#68]
After our discussion today @betatim: 

Somehow running `py.test` still fails for me when running it locally, even when there's no `.osfcli.config` present in the `osf-cli` folder. I tried a fresh clone of this repo and it gives `6 failed, 60 passed in 1.76 seconds` and in all 6 cases the error is the following:

`AttributeError: <module 'osfclient.cli' from '…/osf-cli/osfclient/cli.py'> does not have the attribute 'open'`

I've tested on `Python 3.4.4` and `Python 2.7.12`.

**Comment by betatim** [comment]
Just created a fresh conda environment with python3.6 and python 2.7.13, can't reproduce this :-/ How do you install python? Can you try in a new virtual env or conda environment?

Can you tell me one of the tests that fail?

What does `which py.test` say?

**Comment by gedankenstuecke** [comment]
Found the problem, somehow an old (1.x) version of mock was stuck, i forced an upgrade and now it worked! 🎉
