### ISSUE TITLE
Rsync style --delete option?

### ISSUE THREAD

**Issue by benlindsay** [dib-lab/osf-cli#98]
Maybe this would be hard to do, but it would be great if there was a way to include a `--delete` option when doing a recursive upload so that if a file has been deleted locally, the file will also be deleted in the OSF project, maybe asking for permission for each file by default.

**Comment by betatim** [comment]
Started thinking about how to keep local and remote in sync in #79. Should we move this discussion there? (If yes close this one)

**Comment by benlindsay** [comment]
Yes, I agree.
